//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystemEnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int idClient { get; set; }
        public string passwordClient { get; set; }
        public string loginClient { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string city { get; set; }
    }
}
